import React, { useState } from 'react';
import { 
  Sparkles, RefreshCw, CheckSquare, Square, 
  Copy, Download, Check, AlertCircle, HelpCircle, 
  ListOrdered, FileDown 
} from 'lucide-react';

export function AINotesPanel({
  notesData,
  isGenerating = false,
  onGenerateNotes,
  onUpdateNotes,
  transcriptCount = 0,
}) {
  const [copied, setCopied] = useState(false);
  const [completedTasks, setCompletedTasks] = useState({});

  const toggleTask = (index) => {
    const items = notesData?.actionItems || [];
    if (onUpdateNotes) {
      onUpdateNotes({
        ...notesData,
        actionItems: items.map((item, itemIndex) => itemIndex === index
          ? { ...item, isCompleted: !Boolean(item.isCompleted) }
          : item),
      });
    } else {
      setCompletedTasks((previous) => ({ ...previous, [index]: !previous[index] }));
    }
  };

  const getPriorityBadge = (priority) => {
    switch (priority?.toLowerCase()) {
      case 'high':
        return 'bg-[#fae8e4] text-[#a85f51] border-[#f0d2ca]';
      case 'medium':
        return 'bg-[#f7f0df] text-[#92773f] border-[#eadfbe]';
      default:
        return 'bg-[#edf0e8] text-[#687950] border-[#dce4cf]';
    }
  };

  // Export to Markdown string
  const generateMarkdownString = () => {
    if (!notesData) return '';
    return `# Meeting Summary & Action Items
*Generated by SyncMeet AI on ${new Date().toLocaleDateString()}*

## 📝 Executive Summary
${notesData.summary || 'No summary available.'}

## 🎯 Key Decisions Made
${notesData.decisions?.map(d => `- ${d}`).join('\n') || '- None'}

## ✅ Action Items
${notesData.actionItems?.map((a, i) => `- [${a.isCompleted ?? completedTasks[i] ? 'x' : ' '}] **${a.task}** (Assignee: ${a.assignee} | Priority: ${a.priority})`).join('\n') || '- None'}

## ❓ Open Questions & Next Steps
${notesData.openQuestions?.map(q => `- ${q}`).join('\n') || '- None'}
`;
  };

  const handleCopyMarkdown = () => {
    const md = generateMarkdownString();
    navigator.clipboard.writeText(md).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const handleDownloadFile = (type = 'md') => {
    let content = '';
    let filename = `Meeting-Notes-${Date.now()}.${type}`;
    let mime = 'text/markdown';

    if (type === 'json') {
      content = JSON.stringify(notesData, null, 2);
      mime = 'application/json';
    } else {
      content = generateMarkdownString();
    }

    const blob = new Blob([content], { type: mime });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex flex-col h-full overflow-hidden select-none">
      {/* Top Action Bar */}
      <div className="flex items-center justify-between border-b border-[#ecece7] bg-white px-3.5 py-3">
        <div className="flex items-center gap-2">
          <Sparkles className="h-4 w-4 text-[#9aab76]" />
          <span className="text-xs font-bold text-[#32342e]">Key points</span>
        </div>

        <button
          type="button"
          onClick={onGenerateNotes}
          disabled={isGenerating || transcriptCount === 0}
          className={`flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-semibold transition-all ${
            isGenerating
              ? 'animate-pulse cursor-not-allowed bg-[#eff0eb] text-[#8b8e85]'
              : 'bg-[#171815] text-white hover:bg-[#363831] active:scale-95'
          }`}
        >
          <RefreshCw className={`w-3.5 h-3.5 ${isGenerating ? 'animate-spin' : ''}`} />
          <span>{isGenerating ? 'Synthesizing...' : 'Update Notes'}</span>
        </button>
      </div>

      {/* Notes Scroll Content */}
      <div className="flex-1 overflow-y-auto p-4 space-y-5">
        {!notesData ? (
          <div className="flex h-full flex-col items-center justify-center p-6 text-center text-[#85887f]">
            <div className="mb-3 flex h-12 w-12 items-center justify-center rounded-2xl border border-[#e5eadb] bg-[#f0f4e9]">
              <Sparkles className="h-6 w-6 text-[#8fa765]" />
            </div>
            <h3 className="mb-1 text-sm font-semibold text-[#393b35]">No AI notes yet</h3>
            <p className="mb-4 max-w-[240px] text-xs text-[#85887f]">
              Speak in the meeting to build the transcript, then click below to generate instant summaries.
            </p>
            <button
              onClick={onGenerateNotes}
              disabled={transcriptCount === 0}
              className="flex items-center gap-2 rounded-xl bg-[#171815] px-4 py-2 text-xs font-semibold text-white transition-all hover:bg-[#363831] disabled:opacity-40"
            >
              <Sparkles className="w-3.5 h-3.5" />
              <span>Generate AI Notes ({transcriptCount} dialog lines)</span>
            </button>
          </div>
        ) : (
          <>
            {/* 1. Executive Summary */}
            <div className="rounded-2xl border border-[#ecece7] bg-white p-4">
              <div className="flex items-center justify-between mb-1.5">
                <span className="text-[10px] font-bold uppercase tracking-wider text-[#9b7863]">
                  {notesData.generationSource === 'gemini_api' ? 'AI summary' : 'Transcript summary'}
                </span>
                {notesData.generationSource && notesData.generationSource !== 'gemini_api' && (
                  <span className="text-[10px] text-[#92958d]">Draft</span>
                )}
              </div>
              <p className="text-xs leading-relaxed text-[#50534b]">
                {notesData.summary}
              </p>
            </div>

            {/* 2. Key Decisions */}
            {notesData.decisions && notesData.decisions.length > 0 && (
              <div className="rounded-2xl border border-[#ecece7] bg-white p-4">
                <span className="mb-2 block text-[10px] font-bold uppercase tracking-wider text-[#829866]">
                  Key Decisions Agreed
                </span>
                <ul className="space-y-2">
                  {notesData.decisions.map((decision, i) => (
                    <li key={i} className="flex items-start gap-2 text-xs text-[#50534b]">
                      <span className="font-bold text-[#9bb776]">•</span>
                      <span>{decision}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* 3. Action Items */}
            {notesData.actionItems && notesData.actionItems.length > 0 && (
              <div className="rounded-2xl border border-[#ecece7] bg-white p-4">
                <span className="mb-2.5 block text-[10px] font-bold uppercase tracking-wider text-[#9b7863]">
                  Action Items & Deliverables
                </span>
                <div className="space-y-2.5">
                  {notesData.actionItems.map((item, index) => {
                    const isDone = Boolean(item.isCompleted ?? completedTasks[index]);
                    return (
                      <button
                        key={item.id || index}
                        type="button"
                        aria-pressed={Boolean(item.isCompleted ?? completedTasks[index])}
                        onClick={() => toggleTask(index)}
                        className={`w-full p-2.5 rounded-xl border text-left transition-all cursor-pointer flex items-start gap-2.5 ${
                          isDone
                            ? 'border-[#edf0e9] bg-[#f6f7f3] opacity-50'
                            : 'border-[#ecece7] bg-[#fafaf8] hover:bg-[#f3f4ef]'
                        }`}
                      >
                        <span className="mt-0.5 text-[#9b7863]">
                          {isDone ? (
                            <CheckSquare className="h-4 w-4 text-[#8aa767]" />
                          ) : (
                            <Square className="h-4 w-4 text-[#a1a39c]" />
                          )}
                        </span>
                        <div className="flex-1">
                          <p className={`text-xs text-[#50534b] ${isDone ? 'line-through text-[#92958d]' : ''}`}>
                            {item.task}
                          </p>
                          <div className="flex items-center gap-2 mt-1.5">
                            <span className="rounded-md bg-[#f5eee7] px-2 py-0.5 text-[10px] font-medium text-[#8d715c]">
                              👤 {item.assignee || 'Unassigned'}
                            </span>
                            <span className={`text-[10px] font-semibold px-2 py-0.5 rounded-md border ${getPriorityBadge(item.priority)}`}>
                              {item.priority || 'Medium'}
                            </span>
                          </div>
                        </div>
                      </button>
                    );
                  })}
                </div>
              </div>
            )}

            {/* 4. Open Questions */}
            {notesData.openQuestions && notesData.openQuestions.length > 0 && (
              <div className="rounded-2xl border border-[#ecece7] bg-white p-4">
                <span className="mb-2 block text-[10px] font-bold uppercase tracking-wider text-[#9a8051]">
                  Open Questions / Parking Lot
                </span>
                <ul className="space-y-2">
                  {notesData.openQuestions.map((q, i) => (
                    <li key={i} className="flex items-start gap-2 text-xs text-[#50534b]">
                      <HelpCircle className="mt-0.5 h-3.5 w-3.5 shrink-0 text-[#a78c58]" />
                      <span>{q}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </>
        )}
      </div>

      {/* Bottom Export Bar */}
      {notesData && (
        <div className="flex items-center gap-2 border-t border-[#ecece7] bg-white p-3">
          <button
            type="button"
            onClick={handleCopyMarkdown}
            className="flex flex-1 items-center justify-center gap-1.5 rounded-xl bg-[#f1f2ee] px-3 py-2.5 text-xs font-semibold text-[#4d5048] transition-all hover:bg-[#e8eae3] active:scale-95"
          >
            {copied ? <Check className="h-3.5 w-3.5 text-[#809a5e]" /> : <Copy className="h-3.5 w-3.5" />}
            <span>{copied ? 'Copied MD!' : 'Copy Markdown'}</span>
          </button>

          <button
            type="button"
            onClick={() => handleDownloadFile('md')}
            className="rounded-xl border border-[#e9e9e4] bg-white p-2.5 text-[#777a72] transition-all hover:bg-[#f3f4ef]"
            title="Download as .md file"
          >
            <FileDown className="w-4 h-4" />
          </button>

          <button
            type="button"
            onClick={() => handleDownloadFile('json')}
            className="rounded-xl bg-[#f1f2ee] p-2.5 text-xs font-mono text-[#686b63] transition-all hover:bg-[#e8eae3]"
            title="Download JSON schema"
          >
            JSON
          </button>
        </div>
      )}
    </div>
  );
}
